# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3366:3306
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  db: